name: Server Tests

on:
  push:
    branchs:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.5
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        run: swift test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
